server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/productdb?createDatabaseIfNotExist=true
    username: root
    password: Iswarya24!
  jpa:
    hibernate:
      ddl-auto: update
